using System;

namespace NavigationLib.UseCases
{
    /// <summary>
    ///     Represents the result of a navigation operation (return value from Use Cases layer).
    ///     This class is immutable, with all properties set via the constructor and only factory methods for instantiation.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         This is the result type used by the Use Cases layer, generated by NavigationService.
    ///         External users receive navigation results through NavigationLib.Adapters.NavigationHostResult.
    ///     </para>
    ///     <para>
    ///         It is recommended to use the <see cref="CreateSuccess" /> and <see cref="CreateFailure" /> static factory methods to create instances.
    ///     </para>
    /// </remarks>
    internal class NavigationResult
    {
        /// <summary>
        ///     Initializes a new instance of the NavigationResult class.
        /// </summary>
        /// <param name="success">Whether the navigation was successful.</param>
        /// <param name="failedAtSegment">The segment name where navigation failed (null if successful).</param>
        /// <param name="errorMessage">The error message (null if successful).</param>
        /// <param name="exception">The thrown exception (if any).</param>
        public NavigationResult(bool success, string failedAtSegment, string errorMessage, Exception exception)
        {
            Success         = success;
            FailedAtSegment = failedAtSegment;
            ErrorMessage    = errorMessage;
            Exception       = exception;
        }

        /// <summary>
        ///     Gets a value indicating whether the navigation was successful.
        /// </summary>
        public bool Success { get; }

        /// <summary>
        ///     Gets the segment name (region name) where navigation failed.
        ///     If navigation was successful, the value is null.
        /// </summary>
        public string FailedAtSegment { get; }

        /// <summary>
        ///     Gets the error message when navigation failed.
        ///     If navigation was successful, the value is null.
        /// </summary>
        public string ErrorMessage { get; }

        /// <summary>
        ///     Gets the exception thrown during the navigation process (if any).
        ///     If no exception occurred, the value is null.
        /// </summary>
        public Exception Exception { get; }

        /// <summary>
        ///     Creates a NavigationResult representing a successful navigation.
        /// </summary>
        /// <returns>A NavigationResult instance representing success.</returns>
        /// <example>
        ///     <code>
        /// var result = NavigationResult.CreateSuccess();
        /// if (result.Success)
        /// {
        ///     Console.WriteLine("Navigation completed successfully.");
        /// }
        /// </code>
        /// </example>
        public static NavigationResult CreateSuccess() => new NavigationResult(true, null, null, null);

        /// <summary>
        ///     Creates a NavigationResult representing a failed navigation.
        /// </summary>
        /// <param name="failedAtSegment">The segment name where navigation failed.</param>
        /// <param name="errorMessage">A description of the failure reason.</param>
        /// <param name="exception">The associated exception (optional).</param>
        /// <returns>A NavigationResult instance representing failure.</returns>
        /// <exception cref="ArgumentNullException">
        ///     Thrown when <paramref name="errorMessage" /> is null.
        /// </exception>
        /// <example>
        ///     <code>
        /// var result = NavigationResult.CreateFailure("Level1", "Region not found within timeout.");
        /// if (!result.Success)
        /// {
        ///     Console.WriteLine($"Navigation failed at {result.FailedAtSegment}: {result.ErrorMessage}");
        /// }
        /// </code>
        /// </example>
        public static NavigationResult CreateFailure(string failedAtSegment, string errorMessage, Exception exception = null)
        {
            if (errorMessage == null)
            {
                throw new ArgumentNullException(nameof(errorMessage));
            }

            return new NavigationResult(false, failedAtSegment, errorMessage, exception);
        }

        /// <summary>
        ///     Returns a string representation of the current instance.
        /// </summary>
        /// <returns>A string containing detailed information about the navigation result.</returns>
        public override string ToString()
        {
            if (Success)
            {
                return "NavigationResult: Success";
            }

            return $"NavigationResult: Failed at '{FailedAtSegment ?? "(unknown)"}' - {ErrorMessage ?? "(no message)"}";
        }
    }
}
